CREATE TABLE IF NOT EXISTS Category(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS User(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    register_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    contacts VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Lot(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    creating_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    image VARCHAR(100) NOT NULL,
    start_price INT NOT NULL,
    end_date DATE NOT NULL,
    step INT NOT NULL,

    authorId INT NOT NULL,
    CONSTRAINT lot_author_fk
    FOREIGN KEY (authorId) REFERENCES User (Id) ON DELETE CASCADE,

    winnerId INT NULL,
    CONSTRAINT lot_winner_fk
    FOREIGN KEY (winnerId) REFERENCES User (Id) ON DELETE CASCADE,

    categoryId INT NOT NULL,
    CONSTRAINT lot_category_fk
    FOREIGN KEY (categoryId) REFERENCES Category (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bet(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    summ INT NOT NULL,
    
    userId INT NOT NULL,
    CONSTRAINT bet_user_fk
    FOREIGN KEY (userId) REFERENCES User (Id) ON DELETE CASCADE,

    lotId INT NOT NULL,
    CONSTRAINT bet_lot_fk
    FOREIGN KEY (lotId) REFERENCES Lot (Id) ON DELETE CASCADE
);

ALTER TABLE Lot ADD FULLTEXT(name, description);
